apiVersion: analysis.crane.io/v1alpha1
kind: RecommendationConfiguration
recommenders:
  - name: Replicas
    acceptedResources:
      - kind: Deployment
        apiVersion: apps/v1
      - kind: StatefulSet
        apiVersion: apps/v1
  - name: Resource
    acceptedResources:
      - kind: Deployment
        apiVersion: apps/v1
      - kind: StatefulSet
        apiVersion: apps/v1
  - name: IdleNode
    acceptedResources:
      - kind: Node
        apiVersion: v1
  - name: HPA
    acceptedResources:
      - kind: Deployment
        apiVersion: apps/v1
      - kind: StatefulSet
        apiVersion: apps/v1
