apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: greedy
description: Priority for low level.
value: -100

---

apiVersion: v1
kind: Pod
metadata:
  name: low
spec:
  containers:
    - image: docker.io/gocrane/stress-ng:v0.12.09
      imagePullPolicy: Always
      name: low
      command:
      - stress-ng
      - -c
      - "3"
      - --cpu-method
      - cpuid
  priorityClassName: greedy