{{ if eq .Values.smtp.host "" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-mailmock
  labels:
    app: mailmock
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: mailmock
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: mailmock
        image: mist/mailmock
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8025
          name: smtp
        - containerPort: 8143
          name: imap
        resources:
          requests:
            memory: 50Mi
            cpu: 10m
          limits:
            memory: 100Mi
            cpu: 200m
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- end }}
