name: Auto message for PR's and Issues
# description: Automatically send hello message to the first PR and Issue for new contributor.
on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
jobs:
  build:
    name: Hello new contributor
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hey, thank you for opening your first Issue! 🙂 While an Oraculi team member takes a look at your issue we would like to invite you to join our official Discord server, where you can interact directly with other contributors and Oraculi team members. Link here: https://discord.oraculi.io"
          pr-message: "Hey, thank you for opening your Pull Request ! 🙂 While an Oraculi team member takes a look at your PR we would like to invite you to join our official Discord server, where you can interact directly with other contributors and Oraculi team members. Link here: https://discord.oraculi.io"